# Uncomment the next line to define a global platform for your project
platform :ios, '14.4'

target 'Streakz' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Streakz
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'FBSDKLoginKit'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift', '~> 7.0-beta'
  pod 'Firebase/Storage'

end
